---
- name: Docker Engine
  hosts: verleih
  become: true

  tasks:
    - name: Konfliktpakete sind nicht installiert
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
          - docker-compose-v2
          - docker-doc
          - podman-docker
        state: absent

    - name: Ordner für apt-Schlüssel existiert
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Signaturschlüssel von Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        owner: root
        group: root
        mode: "0644"

    - name: Docker-Paketquelle
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.sources
        content: |
          Types: deb
          URIs: https://download.docker.com/linux/ubuntu
          Suites: {{ ansible_distribution_release }}
          Components: stable
          Architectures: amd64
          Signed-By: /etc/apt/keyrings/docker.asc
        owner: root
        group: root
        mode: "0644"

    - name: Docker-Pakete sind installiert
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Docker-Dienst läuft und startet beim Booten
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started
